### ISSUE TITLE
Issues with new esg.cmip6.ini file

### ISSUE THREAD

**Issue by agstephens** [ESGF/config#20]
@alaniwi has made some observations of the current `esg.cmip6.ini` file in the devel branch. I have captured them all in this Issue:

1.  What are the square brackets in `filename_format` meant to represent? I think the whole thing is meant to be a regexp.
2. None of the other `ini` files have a leading `/` in `directory_format`
3. `frequency` is used in `dataset_name_format` but it doesn't seem to be defined anywhere.
4. There are numerous `'` and `"` symbols in the text in the descriptions column of experiment_options table. I wonder if they might need escaping with `\` to avoid breaking `ini` file parsing (I haven't tested this, but the colourisation in emacs is treating them as string delimiters, rightly or wrongly).

**Comment by glevava** [comment]
1. Square brackets are for optional filename elements (e.g., start/end date in CMIP case)? That's the case for filename with "fx" frequency. 
2. Leading '/' is optional and doesn't change anything in the regex matching (at least for 'esgprep' subcommands.
3. That's a mistake, 'frequency' should be removed rom the dataset_name_format.
4. I don't know if this could lead to some side-effect. My opinion is to remove them as the other ini files doesn't include such characters.

**Comment by sashakames** [comment]
Reopening because the automated file generation script will need to reflect that.  It would be helpful to know which symbol characters that impact file parsing appear in the descriptions so they can be simply removed.  For our purposes having perfect punctuation doesn't matter.

**Comment by glevava** [comment]
Ok Sasha, in the new version I just removed simple and double quotes from experiment description.
