### ISSUE TITLE
member_id vs ensemble in cmip6 config

### ISSUE THREAD

**Issue by MartinaSt** [ESGF/config#29]
It seems to me that the current cmip6 config file does use ensemble instead of member_id in the DRS and the dataset_id. 

The global attributes, DRS etc. paper (http://goo.gl/v1drZl ) specifies the member_id as:
```
if sub_experiment_id = “none”
        member_id = <variant_label>
else
        member_id = <sub_experiment_id>-<variant_label>
endif
```
where variant_label complys with the ensemble_pattern of the cmip6 config file. It is usually fine to use the variant_label (ensemble), except for the DCPP (decadal) data, which has the start year as sub_experiment_id (see examples given in the global attributes paper).

**Comment by sashakames** [comment]
This has been corrected to member_id / variant_label
