### ISSUE TITLE
Update esg.cmip6.ini

### ISSUE THREAD

**Issue by durack1** [ESGF/config#51]
It seems the `esgf.cmip6.ini` file is no longer in-sync with the latest CMIP6_CVs entries (v6.2.56.10, see [here](https://github.com/WCRP-CMIP/CMIP6_CVs)).

In particular, the `IPSL-CM7A-ATM-*` models were deregistered on the 18th Feb 2022 (see [here](https://github.com/WCRP-CMIP/CMIP6_CVs/pull/1057)).

Wondering whether synchronization of these changes should be automated?

**Comment by sashakames** [comment]
Automation has been something left outstanding for years.

**Comment by sashakames** [comment]
We now have this running in a crontab at LLNL

**Comment by durack1** [comment]
@sashakames excellent, thanks for sorting this!
